---
name: tests
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 0' # weekly
jobs:
  tests:
    timeout-minutes: 30
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ["3.6"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          sudo apt-get -y install libxml2-dev libxslt-dev
          pip install .
          pip install -r requirements/lint.txt
          pip install -r requirements/main.txt
          pip install -r requirements/test.txt
          pip install codecov mock
      - name: Lint
        run: |
          flake8 cnxtransforms/ tests/
      - name: Test
            # Note: The --ignore=src in the py.test invocation below is due to
            # the git dependencies for cnx-archive being
            # pulled to ./src on the CI server.
        run: |
          py.test --cov=cnxtransforms --ignore=src
          codecov
